/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIConfigForm: typeof import('./components/config/AIConfigForm.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    CheckinPointsDisplay: typeof import('./components/salary/CheckinPointsDisplay.vue')['default']
    DateField: typeof import('./components/questionnaire/DateField.vue')['default']
    DropdownField: typeof import('./components/questionnaire/DropdownField.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FieldPropertyEditor: typeof import('./components/questionnaire/FieldPropertyEditor.vue')['default']
    FieldRenderer: typeof import('./components/questionnaire/FieldRenderer.vue')['default']
    GroupField: typeof import('./components/questionnaire/GroupField.vue')['default']
    InterviewChat: typeof import('./components/interview/InterviewChat.vue')['default']
    MessageBubble: typeof import('./components/interview/MessageBubble.vue')['default']
    MultipleChoiceField: typeof import('./components/questionnaire/MultipleChoiceField.vue')['default']
    NumberField: typeof import('./components/questionnaire/NumberField.vue')['default']
    PoolSummaryCard: typeof import('./components/salary/PoolSummaryCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleChoiceField: typeof import('./components/questionnaire/SingleChoiceField.vue')['default']
    TextField: typeof import('./components/questionnaire/TextField.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
